### ISSUE TITLE
how to change the time format in ticket center?

### ISSUE THREAD

**Issue by fang-yu** [nanodesigns/nanosupport#49]
The default time format in the ticket center is like : 30 Oct 2017 07:26PM, but this is English format, how could I change it to my country fomat like:

![](http://cdn.bpteach.com/17-11-1/51855178.jpg)

Thank!

**Comment by mayeenulislam** [comment]
Good point.
But we're afraid, with `v0.4.1`, it's not possible as [_that_ portion's hard coded](https://github.com/nanodesigns/nanosupport/blob/v0.4.1/includes/shortcodes/ns-support-desk.php#L165-L167).
But on the next release we'll use the WP Settings, so that user can get control, inshALLAH.
Taking it as a limitation.

**Comment by mayeenulislam** [comment]
For Legacy datetime format, with this change on the next release (inshALLAH), user can modify as they with whether using the WordPress settings, or using the new filter hook:
