### ISSUE TITLE
User can't read gis ticket

### ISSUE THREAD

**Issue by Qamdad** [nanodesigns/nanosupport#57]
### Actual behavior

After user submit new ticket it becomes pending and after support team answer ith will cahnge to open status. But user who created the ticket can't open and read th answer because when he try it show him 404 page (not found page)

### Steps to reproduce

1. Change premalinks 
2. Disable all plugin

### System Status

NanoSupport Environment
WordPress version	4.9.8
NanoSupport version	0.5.0
E-Commerce?	Disabled
Active Theme	Bemobile – 1.2
Debug mode	Off
Multisite?	No
Site Language	en_US
Server	Apache
PHP Memory Limit	768 MB
PHP version	7.2.8
MySQL version	5.6.36

**Comment by mayeenulislam** [comment]
I'm afraid, your issue is not clear to us. Pending ticket are not clickable. After opening/answering a ticket from Agent, we can easily browse them.

Your steps to reproduce is not clear. _Change permalinks_ to _what_? What with _disabling all plugin_!

Could you please see issue #27? Is that your issue?

Could you please rewrite your issue with more authentic details. We can't reproduce your issue with the details you provided.

**Comment by Qamdad** [comment]
User can't open his ticket it show him 404 page all the time he would like to read the ticket submitted by him. 

You can check this gif to make it more clear. https://giphy.com/gifs/1eso5YnXVfQxBpXFyy

**Comment by mayeenulislam** [comment]
Hmm. That looks bad. But we're afraid, we cannot recreate the issue here.

## Workaround
Let's try to solve this by flushing rewrite rules:

1. Please get to the admin panel
2. Settings &raquo; Permalinks
3. Do _nothing_ and Save Changes to flush rewrite rules

You can also Deactivate and Reactivate the plugin from Admin panel &raquo; Plugins

Please let's know what happened then.

**Comment by Qamdad** [comment]
I solve it by set User Role to be subscriber. Because I'm using private content plugin which set New User Default Role to be privatecontent. Now any users with default WP role have no issue. 

Thanks for thr Great free plugin with premium features.

**Comment by mayeenulislam** [comment]
Good to hear that the issue is resolved.
Thanks for the nice comments. :heart: 
Would love to have [your review](https://wordpress.org/support/plugin/nanosupport/reviews/#new-post) on our plugin. Thank you for using NanoSupport.
