### ISSUE TITLE
Obligatory response and character requirement on support seeker side

### ISSUE THREAD

**Issue by nezam05** [nanodesigns/nanosupport#8]
If a ticket gets responded and support seeker want to close the ticket with no response or with simple "thanks" response, she face two warning
Error: Your message is too short. Write down at least 30 characters.
Error: Response field can’t be empty.

I think this should be flexible and both obligation should be removed.

**Comment by mayeenulislam** [comment]
## Issue#1
I'm a regular Support Assistant of [WordPress Development StackExchange](http://wordpress.stackexchange.com/), and there is an obligation for commenting, at least 15 characters are needed there:
![15-char-comment](https://cloud.githubusercontent.com/assets/4551598/17896752/8e3cfd5e-6973-11e6-9f70-f9c900221a3d.png)
so nobody can do _Thank you_ comment.

And aside, we've another review option saying **Low Quality Posts**. Most of the time one/two line answers caught there, because they are not providing anything.
![low-quality-posts](https://cloud.githubusercontent.com/assets/4551598/17897031/70ae5ffc-6974-11e6-8cf0-205f625d42bf.png)


In this context, "Thank you" is not a reply.

We made this obligatory to make the communication more informative.

But if we have more vote on that, we can definitely think something onward.

## Issue#2
**Closing ticket without any reply** is possible from Admin end. Currently (as of `v0.2.1`) not available from Front End.

**Comment by nezam05** [comment]
If I understand correctly, this plugin is for one to one support, as discussions remain private. Since its not intended to be functional like a community like stackexchange, the issue of quality post should not apply, no?

Since this plugin is more like WHMCS ( in terms of one to one support), i think the user should have the capacity to close any issue and with or without posting any reply.

**Comment by mayeenulislam** [comment]
52e0b67b38c5b0a0983f5af493c85fcb935bea61

**Comment by mayeenulislam** [comment]
#52e0b67b38c5b0a0983f5af493c85fcb935bea61
