### ISSUE TITLE
NECESITO AYUDA 

### ISSUE THREAD

**Issue by JerryDelgado** [nanodesigns/nanosupport#87]
Hola gracias por tan excelente producto 
a la hora de la instalación y pruebas  todo se ve muy bien 
pero a la hora de responder o  sea de mi lado o de el lado del que hace la consulta 
sale este error 
(ERROR: Debes aceptar la política de privacidad para enviar comentarios.)
El problema es que no me da opciones para aceptar políticas y para tener alguna acción 
espero si respuesta y ayuda pronto

**Comment by mayeenulislam** [comment]
Hello @JerryDelgado actually we're not Spanish. So Google Translate translated your message to:

> _Hi, thanks for such an excellent product
at the time of installation and testing everything looks great
but at the time of answering either on my side or on the side of the one who makes the query
this error comes out
(BUG: You must accept the privacy policy to post comments.)
The problem is that it doesn't give me options to accept policies and to have any action
I hope if answer and help soon_

What we understood is: You're getting a checkmark saying to accept terms. But actually there is no such code in our plugin. You can check the code in this repo.

It must be coming from another plugin or your theme. Try deactivating all the plugins but NanoSupport, and switch back to a default theme and see whether the issue persists or not.

Thank you for using NanoSupport.

**Comment by JerryDelgado** [comment]
Gracias efectivamente  un complemento  genero el conflicto 
ya esta resulto, gracias por tan excelente trabajo y  por hacer una herramienta tan potente y buena 
YA ESTA RESULTO

**Comment by mayeenulislam** [comment]
Nice to hear that, you sorted out the issue and thanks for the complement.

If you love the plugin you can complement us by giving the plugin a 5-star (⭐️⭐️⭐️⭐️⭐️) review on the wp.org 😃
https://wordpress.org/support/plugin/nanosupport/reviews/#new-post
