### ISSUE TITLE
Post Thumbnails for knowledgebase.

### ISSUE THREAD

**Issue by freimaks** [nanodesigns/nanosupport#88]
Knowledge base posts are generated using a standard template.

Is it possible to add thumbnails for this type of post?

Of course we can use the hook ourselves:
`add_post_type_support( 'nanodoc', 'thumbnail' );`

But I don’t know how legal this is for your plugin.

**Comment by mayeenulislam** [comment]
Thank you for reaching us.
It's 100% legal, because it's GPL licensed. You can change, modify however you want.

But changing directly in the plugin file is not recommended, as they will be wiped out on the next plugin update. For the modification, you can add the code in your theme or in another plugin of your own.
